const CreateVehicle = (vehicleRepository) => {
    return {
        execute: async (vehicleData) => {
            // Validate vehicle data
            if (!vehicleData.name || !vehicleData.model || !vehicleData.owner) {
                throw new Error("Invalid vehicle data");
            }

            // Create vehicle
            const vehicle = {
                id: null, // ID will be generated by the database
                name: vehicleData.name,
                model: vehicleData.model,
                owner: vehicleData.owner,
                maintenanceHistory: []
            };

            // Save vehicle using the repository
            return await vehicleRepository.create(vehicle);
        }
    };
};

export default CreateVehicle;