class CreateUser {
    constructor(userRepository) {
        this.userRepository = userRepository;
    }

    async execute(userData) {
        const { name, email, password, role } = userData;

        // Validate user data (this can be expanded)
        if (!name || !email || !password || !role) {
            throw new Error('All fields are required');
        }

        // Create user entity (this should be defined in the User entity)
        const user = {
            id: null, // This will be generated by the database
            name,
            email,
            password, // In a real application, make sure to hash the password
            role
        };

        // Save user to the repository
        const createdUser = await this.userRepository.create(user);
        return createdUser;
    }
}

export default CreateUser;